Added calc social graph diameter Python prototype
hjirthdzehk/degreesOfSeparation pull request #1
Opened 2016-09-30 20:37 UTC by VladVin

2016-09-30 22:01 UTC, kiselev-anton requested changes

2016-09-30 22:01 UTC, kiselev-anton commented on vladvin_prototype/calc_social_graph_diameter.py
> +        self.__access_token = 'fb718ae5a7d94dd78a092605939e1eb4a5da033b40b574bdec24c665ef58f3d3ca84533087f8a3a967eb0'
Ты мог бы использовать метод из vk_handler.py

2016-09-30 22:01 UTC, kiselev-anton commented on vladvin_prototype/calc_social_graph_diameter.py
> +
```python
return all(user_id in handshakes for user_id in user_ids)

2016-09-30 22:01 UTC, kiselev-anton commented on vladvin_prototype/calc_social_graph_diameter.py
> +            print handshakes
Оберни аргумент `print` в скобки, остальная часть проекта на Python 3.

2016-10-01 10:11 UTC, VladVin commented on vladvin_prototype/calc_social_graph_diameter.py
> +        self.__access_token = 'fb718ae5a7d94dd78a092605939e1eb4a5da033b40b574bdec24c665ef58f3d3ca84533087f8a3a967eb0'
Я не использую библиотеку с Vk API. Делаю http запросы, думаю, этого достаточно для прототипа

2016-10-01 10:13 UTC, kiselev-anton approved these changes

2016-10-01 10:14 UTC, merged